name: Update data Workflow

on:
  schedule:
    # Runs at 04:00 UTC every day
    # '0 4 * * *', '*/10 * * * *'
    - cron: '0 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Setup Miniconda
       uses: conda-incubator/setup-miniconda@v3
       with:
         activate-environment: seaice
         environment-file: environment.yaml
         python-version: 3.9
         auto-activate-base: false
         
     - name: Add conda to system path
       run: |
        echo $CONDA/bin >> $GITHUB_PATH
        
     - name: Install Dependencies          
       run: conda env update --file environment.yaml --name seaice
       
     - name: Run Python script
       run: |
        conda init bash
        conda activate seaice
        python scripts/update_daily_extent.py  # This script updates CSV files in data/

     - name: Commit and push if changes
       run: |
        git config --global user.email "sun.bak-hospital@noaa.gov"
        git config --global user.name "Sunny Hospital"
        git add data/*.csv
        git commit -m "Update CSV data" || echo "No changes to commit"
        git push
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      
           
         
        
    
